// SPDX-License-Identifier: AGPL-3.0-or-later
//
// PairedDeviceStore.swift
// Sprint 17 (2026-06-23): persistent pairing + remote-revoke.
//
// Loupe previously paired a host and a controller via a one-shot QR
// scan. The session was transient: closing the host app, restarting
// the iPhone, or even losing WebSocket connectivity required a new
// QR. This module stores the pairing record on the host so the
// host recognises the controller on subsequent launches and the
// user can revoke a stolen or lost controller from the host UI
// (or remotely via the signaling-server `/v1/relay/pairings`
// endpoint).
//
// The store is JSON-on-disk, written atomically. It is **not** the
// long-lived identity key (that lives in Keychain via
// `KeychainKeyStorage`); it is the *peer identity* for each paired
// controller plus the per-peer session key needed to re-establish
// a WebRTC connection without a fresh QR.

import Foundation
import CryptoKit

/// One paired controller's metadata + session keys.
public struct PairedDevice: Codable, Equatable, Sendable, Identifiable {
    /// Stable identifier we generate on first pairing. We surface
    /// it to the user as the "device name" in the host UI.
    public let id: UUID

    /// Friendly name the user assigned (e.g. "Miggu's iPhone").
    public var displayName: String

    /// Public key of the controller's long-lived identity key
    /// (Curve25519 signing key). Used to verify the controller's
    /// signed pairing message on reconnect.
    public let controllerPublicKey: Data

    /// Session key for the WebRTC data channel (32 bytes). Randomly
    /// generated by the host on first pairing; rotated on each
    /// successful reconnect.
    public var sessionKey: Data

    /// Date of last successful WebRTC connection (any state).
    public var lastSeen: Date

    /// Date of first pairing.
    public var createdAt: Date

    /// `true` after the user has revoked the device. Revoked
    /// records stay in the store for audit purposes; the host
    /// refuses to reconnect to a revoked device.
    public var isRevoked: Bool

    public init(
        id: UUID = UUID(),
        displayName: String,
        controllerPublicKey: Data,
        sessionKey: Data,
        lastSeen: Date = Date(),
        createdAt: Date = Date(),
        isRevoked: Bool = false
    ) {
        precondition(controllerPublicKey.count == 32, "controller public key must be 32 bytes")
        precondition(sessionKey.count == 32, "session key must be 32 bytes")
        self.id = id
        self.displayName = displayName
        self.controllerPublicKey = controllerPublicKey
        self.sessionKey = sessionKey
        self.lastSeen = lastSeen
        self.createdAt = createdAt
        self.isRevoked = isRevoked
    }
}

/// Public protocol so the host UI and the remote-revoke API can
/// share one code path.
public protocol PairedDeviceStoring: AnyObject, Sendable {
    /// All paired devices, including revoked ones (in chronological
    /// order, oldest first).
    func listDevices() throws -> [PairedDevice]

    /// The non-revoked device matching `id`, if any.
    func device(for id: UUID) throws -> PairedDevice?

    /// Add a brand-new pairing record. The host generates a fresh
    /// session key and writes atomically.
    func addDevice(_ device: PairedDevice) throws

    /// Update an existing record (e.g. rotate the session key,
    /// touch lastSeen, mark as revoked).
    func updateDevice(_ device: PairedDevice) throws

    /// Mark a device as revoked. The record stays in the file for
    /// audit; the host refuses to reconnect to a revoked id.
    func revokeDevice(id: UUID) throws
}

/// On-disk JSON store. Lives under
/// `~/Library/Application Support/Loupe/paired-devices.json`.
public final class PairedDeviceStore: PairedDeviceStoring, @unchecked Sendable {
    private let url: URL
    private let queue = DispatchQueue(label: "org.francois.Loupe.PairedDeviceStore")

    public init(fileURL: URL? = nil) {
        if let fileURL {
            self.url = fileURL
        } else {
            let fm = FileManager.default
            let appSupport = (try? fm.url(
                for: .applicationSupportDirectory,
                in: .userDomainMask,
                appropriateFor: nil,
                create: true
            )) ?? fm.temporaryDirectory
            let dir = appSupport.appendingPathComponent("Loupe", isDirectory: true)
            try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
            self.url = dir.appendingPathComponent("paired-devices.json")
        }
    }

    public func listDevices() throws -> [PairedDevice] {
        try queue.sync { try _load() }
    }

    public func device(for id: UUID) throws -> PairedDevice? {
        try listDevices().first(where: { $0.id == id })
    }

    public func addDevice(_ device: PairedDevice) throws {
        try queue.sync {
            var devices = try _load()
            if devices.contains(where: { $0.controllerPublicKey == device.controllerPublicKey }) {
                throw PairedDeviceStoreError.duplicatePublicKey
            }
            devices.append(device)
            try _save(devices)
        }
    }

    public func updateDevice(_ device: PairedDevice) throws {
        try queue.sync {
            var devices = try _load()
            guard let idx = devices.firstIndex(where: { $0.id == device.id }) else {
                throw PairedDeviceStoreError.deviceNotFound
            }
            devices[idx] = device
            try _save(devices)
        }
    }

    public func revokeDevice(id: UUID) throws {
        try queue.sync {
            var devices = try _load()
            guard let idx = devices.firstIndex(where: { $0.id == id }) else {
                throw PairedDeviceStoreError.deviceNotFound
            }
            devices[idx].isRevoked = true
            devices[idx].lastSeen = Date()
            try _save(devices)
        }
    }

    // MARK: - Disk I/O

    private func _load() throws -> [PairedDevice] {
        guard FileManager.default.fileExists(atPath: url.path) else { return [] }
        let data = try Data(contentsOf: url)
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode([PairedDevice].self, from: data)
    }

    private func _save(_ devices: [PairedDevice]) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(devices)
        // Atomic write: tmp + rename.
        let tmpURL = url.appendingPathExtension("tmp")
        try data.write(to: tmpURL, options: .atomic)
        if FileManager.default.fileExists(atPath: url.path) {
            _ = try FileManager.default.replaceItemAt(url, withItemAt: tmpURL)
        } else {
            try FileManager.default.moveItem(at: tmpURL, to: url)
        }
        // POSIX 0600 — paired-device.json contains session keys,
        // so the file must not be world-readable.
        try FileManager.default.setAttributes(
            [.posixPermissions: NSNumber(value: 0o600)],
            ofItemAtPath: url.path
        )
    }
}

public enum PairedDeviceStoreError: Error, Equatable {
    case duplicatePublicKey
    case deviceNotFound
    case malformedJSON
}
