// SPDX-License-Identifier: AGPL-3.0-or-later
//
// PairedHostStore.swift
// Sprint 17 (2026-06-23): persistent pairing on the iOS controller.
//
// The controller (iPhone / iPad) used to forget the host after a
// QR scan. Sprint 17 adds a persistent record of the host identity
// so the controller can re-connect on subsequent launches without
// a new QR, and so the user can see the list of hosts they've
// paired from the iOS Settings sheet (and revoke any of them).
//
// Like the host-side `PairedDeviceStore`, this is JSON-on-disk
// under the iOS app's container, scoped to one iOS device. It
// stores the host's public key (so we can verify signed pairing
// messages on reconnect), a friendly name, the last-seen timestamp,
// and the host's session key (so we don't need a fresh QR to
// re-derive the WebRTC data-channel key).

import Foundation
import CryptoKit

public struct PairedHost: Codable, Equatable, Sendable, Identifiable {
    /// Stable identifier for the host. Generated by the controller
    /// on first pairing (UUID v4).
    public let id: UUID

    /// Friendly name shown in the iOS settings list. Defaults to
    /// "<host display name>" from the QR.
    public var displayName: String

    /// Host's long-lived public key (Curve25519 signing key, 32 bytes).
    public let hostPublicKey: Data

    /// Host's per-session key for the WebRTC data channel (32 bytes).
    public var sessionKey: Data

    /// URL of the signaling endpoint used during pairing.
    /// Stored so the controller can re-connect without re-entering
    /// the URL (e.g. wss://signaling.theloupe.team).
    public let signalingURL: String

    /// Last successful connection timestamp.
    public var lastSeen: Date

    /// First pairing timestamp.
    public let createdAt: Date

    /// `true` after the user has revoked this host from the iOS
    /// controller. The host stays in the file for audit; the
    /// controller refuses to reconnect to a revoked host.
    public var isRevoked: Bool

    public init(
        id: UUID = UUID(),
        displayName: String,
        hostPublicKey: Data,
        sessionKey: Data,
        signalingURL: String,
        lastSeen: Date = Date(),
        createdAt: Date = Date(),
        isRevoked: Bool = false
    ) {
        precondition(hostPublicKey.count == 32, "host public key must be 32 bytes")
        precondition(sessionKey.count == 32, "session key must be 32 bytes")
        self.id = id
        self.displayName = displayName
        self.hostPublicKey = hostPublicKey
        self.sessionKey = sessionKey
        self.signalingURL = signalingURL
        self.lastSeen = lastSeen
        self.createdAt = createdAt
        self.isRevoked = isRevoked
    }
}

public protocol PairedHostStoring: AnyObject, Sendable {
    func listHosts() throws -> [PairedHost]
    func host(for id: UUID) throws -> PairedHost?
    func addHost(_ host: PairedHost) throws
    func updateHost(_ host: PairedHost) throws
    func revokeHost(id: UUID) throws
}

/// On-disk JSON store. Lives in the iOS app's `Application Support`
/// directory. Uses POSIX 0600 because the file contains session keys.
public final class PairedHostStore: PairedHostStoring, @unchecked Sendable {
    private let url: URL
    private let queue = DispatchQueue(label: "org.francois.Loupe.PairedHostStore")

    public init(fileURL: URL? = nil) {
        if let fileURL {
            self.url = fileURL
        } else {
            let fm = FileManager.default
            let appSupport = (try? fm.url(
                for: .applicationSupportDirectory,
                in: .userDomainMask,
                appropriateFor: nil,
                create: true
            )) ?? fm.temporaryDirectory
            let dir = appSupport.appendingPathComponent("Loupe", isDirectory: true)
            try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
            self.url = dir.appendingPathComponent("paired-hosts.json")
        }
    }

    public func listHosts() throws -> [PairedHost] {
        try queue.sync { try _load() }
    }

    public func host(for id: UUID) throws -> PairedHost? {
        try listHosts().first(where: { $0.id == id })
    }

    public func addHost(_ host: PairedHost) throws {
        try queue.sync {
            var hosts = try _load()
            if hosts.contains(where: { $0.hostPublicKey == host.hostPublicKey }) {
                throw PairedHostStoreError.duplicatePublicKey
            }
            hosts.append(host)
            try _save(hosts)
        }
    }

    public func updateHost(_ host: PairedHost) throws {
        try queue.sync {
            var hosts = try _load()
            guard let idx = hosts.firstIndex(where: { $0.id == host.id }) else {
                throw PairedHostStoreError.hostNotFound
            }
            hosts[idx] = host
            try _save(hosts)
        }
    }

    public func revokeHost(id: UUID) throws {
        try queue.sync {
            var hosts = try _load()
            guard let idx = hosts.firstIndex(where: { $0.id == id }) else {
                throw PairedHostStoreError.hostNotFound
            }
            hosts[idx].isRevoked = true
            hosts[idx].lastSeen = Date()
            try _save(hosts)
        }
    }

    // MARK: - Disk I/O

    private func _load() throws -> [PairedHost] {
        guard FileManager.default.fileExists(atPath: url.path) else { return [] }
        let data = try Data(contentsOf: url)
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .iso8601
        return try decoder.decode([PairedHost].self, from: data)
    }

    private func _save(_ hosts: [PairedHost]) throws {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys]
        encoder.dateEncodingStrategy = .iso8601
        let data = try encoder.encode(hosts)
        let tmpURL = url.appendingPathExtension("tmp")
        try data.write(to: tmpURL, options: .atomic)
        if FileManager.default.fileExists(atPath: url.path) {
            _ = try FileManager.default.replaceItemAt(url, withItemAt: tmpURL)
        } else {
            try FileManager.default.moveItem(at: tmpURL, to: url)
        }
        try FileManager.default.setAttributes(
            [.posixPermissions: NSNumber(value: 0o600)],
            ofItemAtPath: url.path
        )
    }
}

public enum PairedHostStoreError: Error, Equatable {
    case duplicatePublicKey
    case hostNotFound
    case malformedJSON
}
